### ISSUE TITLE
Sugestie z rozmowy

### ISSUE THREAD

**Issue by kudkudak** [brunokam/robotics-website#1]
Inspiracje: http://cs.stanford.edu/groups/manips/
- Czystszy design
- Obrazek w tle ładniejszy
- Nie powinno być identyczne ze stroną gmum.R
- Dodać slider z obrazkami projektów
- Galeria (KrakRobot, warsztaty)
- Zakladka People
- Zaklada History

Bardziej subiektywne
- Mniej różowego, wiecej bialego
- Wywalic te ikonki (gwiazdki itp)

**Comment by brunokam** [comment]
Rozwińmy temat czystszego designu, bo to jest bardzo ogólne stwierdzenie. Popieram w pełni resztę punktów z górnej części komentarza Staszka.

Jeśli chodzi o te subiektywne, to różu faktycznie jest za dużo, ale nie ja subiektywnie proponuję go zastępować białym, bo w mojej ocenie strona Stanforda jest zbyt biała, a przez to trochę nudna.

O ikonkach chcę poznać jeszcze jakieś opinie, bo akurat gwiazdki można by zastąpić innymi ikonami, ale reszta ikon na stronie mi się podoba.

**Comment by kudkudak** [comment]
Jeszcze bardziej subiektywne opinie:
- Powinny być obrazki na początku strony, jakiś roll z projektmi itp.
- Sekcje powinny być kapitalikami albo zaczynać się z duzych liter (jak szybko patrzyłem duże firmy mają tak rozwiązane onepagery jakie widzialem, np evernote.com, palantir.com craftinity.com ;p )
- Ciągle za dużo różu. Kurde, czemu różowy :( Chyba, ze obecne zmiany jeszcze nie miały na celu zmniejszenie ilości różowego :)

**Comment by igorsieradzki** [comment]
Z większościom uwag Staszka co do treści się zgadzam (galeria, people, history), co do design'u - mniej różu, ikonki mi nie przeszkadzają.
